Repository Team-Sopetit/Sopetit-server, pull requests merged in 2024-04, with the labels that each got.

#216 [REFACTOR] 토큰 재발급 api 리팩토링
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: chan

#217 [ADD] 데일리 루틴 Swagger 정보 추가
  src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineApi.java
Labels: documentation, add, sohyeon

#218 [ADD] 회원의 데일리 루틴 Swagger 정보 추가
  src/main/java/com/soptie/server/memberRoutine/controller/daily/MemberDailyRoutineApi.java
Labels: documentation, add, sohyeon

#220 [ADD] 행복 루틴 Swagger 정보 추가
  src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineApi.java
Labels: documentation, add, seungbin

#219 [ADD] 버전 Swagger 정보 추가
  src/main/java/com/soptie/server/version/controller/VersionApi.java
Labels: documentation, add, sohyeon

#222 [ADD] Swagger 정보 추가
  src/main/java/com/soptie/server/auth/controller/AuthApi.java
  src/main/java/com/soptie/server/doll/controller/DollApi.java
  src/main/java/com/soptie/server/doll/message/ErrorCode.java
  src/main/java/com/soptie/server/member/controller/MemberApi.java
  src/main/java/com/soptie/server/member/entity/Member.java
Labels: add, chan

#214 [REFACTOR] 스웨거 이사 (테스트 가능 ver)
  build.gradle
  src/main/java/com/soptie/server/auth/controller/AuthApi.java
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/soptie/server/common/config/SwaggerConfig.java
  src/main/java/com/soptie/server/common/dto/BaseResponse.java
  src/main/java/com/soptie/server/common/dto/ErrorResponse.java
  src/main/java/com/soptie/server/common/dto/Response.java
  src/main/java/com/soptie/server/common/dto/SuccessResponse.java
  src/main/java/com/soptie/server/common/handler/ErrorHandler.java
  src/main/java/com/soptie/server/doll/controller/DollApi.java
  src/main/java/com/soptie/server/doll/controller/DollController.java
  src/main/java/com/soptie/server/doll/message/ErrorCode.java
  src/main/java/com/soptie/server/member/controller/MemberApi.java
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/MemberDailyRoutineApi.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/controller/happiness/MemberHappinessRoutineApi.java
  src/main/java/com/soptie/server/memberRoutine/controller/happiness/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineApi.java
  src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineApi.java
  src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineController.java
  src/main/java/com/soptie/server/test/TestApi.java
  src/main/java/com/soptie/server/test/TestController.java
  src/main/java/com/soptie/server/version/controller/VersionApi.java
  src/main/java/com/soptie/server/version/controller/VersionController.java
  src/main/resources/application-dev.yml
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
  src/test/java/com/soptie/server/base/BaseControllerTest.java
  src/test/java/com/soptie/server/base/BaseRepositoryTest.java
  src/test/java/com/soptie/server/base/BaseServiceTest.java
  src/test/java/com/soptie/server/doll/controller/DollControllerTest.java
  src/test/java/com/soptie/server/doll/fixture/DollFixture.java
  src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberHappinessRoutineFixture.java
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/fixture/DailyRoutineFixture.java
  src/test/java/com/soptie/server/routine/fixture/HappinessRoutineFixture.java
  src/test/java/com/soptie/server/test/TestControllerTest.java
  src/test/java/com/soptie/server/version/controller/VersionControllerTest.java
Labels: sohyeon, chan, seungbin

#213 [REFACTOR] 데일리 루틴 관련 DTO 네이밍 리팩토링 (sample)
  src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineApi.java
  src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/controller/daily/dto/DailyRoutineListByThemeGetResponse.java
  src/main/java/com/soptie/server/routine/controller/daily/dto/DailyRoutineListByThemesGetResponse.java
  src/main/java/com/soptie/server/routine/controller/daily/dto/DailyThemeListGetResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutineResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesByThemeResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesByThemesResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyThemesResponse.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/daily/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/daily/DailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/daily/dto/DailyRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/routine/service/daily/dto/DailyThemeListGetServiceResponse.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceImplTest.java
Labels: sohyeon

#224 [TEST] 통합 테스트 환경 세팅 & 통합 테스트 테스트
  src/test/java/com/soptie/server/auth/service/AuthServiceImplTest.java
  src/test/java/com/soptie/server/doll/service/DollServiceImplTest.java
  src/test/java/com/soptie/server/member/service/MemberServiceImplTest.java
  src/test/java/com/soptie/server/memberDoll/service/MemberDollServiceImplTest.java
  src/test/java/com/soptie/server/memberRoutine/repository/CompletedMemberDailyRoutineRepositoryTest.java
  src/test/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryTest.java
  src/test/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImplTest.java
  src/test/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImplTest.java
  src/test/java/com/soptie/server/memberRoutine/service/integration/MemberDailyRoutineServiceIntegrationTest.java
  src/test/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryTest.java
  src/test/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryTest.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceImplTest.java
  src/test/java/com/soptie/server/routine/service/HappinessRoutineServiceImplTest.java
  src/test/java/com/soptie/server/support/DatabaseClearListener.java
  src/test/java/com/soptie/server/support/IntegrationTest.java
  src/test/java/com/soptie/server/support/fixture/CompletedMemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/ConversationFixture.java
  src/test/java/com/soptie/server/support/fixture/DailyRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/DailyThemeFixture.java
  src/test/java/com/soptie/server/support/fixture/DollFixture.java
  src/test/java/com/soptie/server/support/fixture/HappinessRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/HappinessSubRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/HappinessThemeFixture.java
  src/test/java/com/soptie/server/support/fixture/MemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/MemberDollFixture.java
  src/test/java/com/soptie/server/support/fixture/MemberFixture.java
  src/test/java/com/soptie/server/support/fixture/MemberHappinessRoutineFixture.java
  src/test/resources/application-test.yml
Labels: sohyeon, test

#226 [REFACTOR] DB 테이블 재구성
  src/main/java/com/soptie/server/expert/entity/Expert.java
  src/main/java/com/soptie/server/memberRoutine/entity/MemberRoutine.java
  src/main/java/com/soptie/server/routine/entity/Routine.java
  src/main/java/com/soptie/server/routine/entity/RoutineType.java
  src/main/java/com/soptie/server/routine/entity/challenge/Challenge.java
  src/main/java/com/soptie/server/theme/entity/ImageInfo.java
  src/main/java/com/soptie/server/theme/entity/Theme.java
Labels: add, sohyeon

#233 [REFACTOR] 회원 데일리 루틴 DTO 분리
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/MemberDailyRoutineApi.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/dto/request/MemberDailyRoutineCreateRequest.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/dto/response/MemberDailyRoutineAchieveResponse.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/dto/response/MemberDailyRoutineCreateResponse.java
  src/main/java/com/soptie/server/memberRoutine/controller/daily/dto/response/MemberDailyRoutineListGetResponse.java
  src/main/java/com/soptie/server/memberRoutine/dto/AchievedMemberDailyRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutineRequest.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutinesResponse.java
  src/main/java/com/soptie/server/memberRoutine/scheduler/MemberDailyRoutineScheduler.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/CompletedMemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/CompletedMemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/dto/request/MemberDailyRoutineAchieveServiceRequest.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/dto/request/MemberDailyRoutineCreateServiceRequest.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/dto/request/MemberDailyRoutineDeleteServiceRequest.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/dto/request/MemberDailyRoutineListGetServiceRequest.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/dto/response/MemberDailyRoutineAchieveServiceResponse.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/dto/response/MemberDailyRoutineCreateServiceResponse.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/dto/response/MemberDailyRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/version/controller/VersionApi.java
  src/main/java/com/soptie/server/version/controller/VersionController.java
  src/main/java/com/soptie/server/version/controller/dto/response/AppVersionGetResponse.java
  src/main/java/com/soptie/server/version/dto/AppVersionResponse.java
  src/main/java/com/soptie/server/version/service/VersionService.java
  src/main/java/com/soptie/server/version/service/VersionServiceImpl.java
  src/main/java/com/soptie/server/version/service/dto/response/AppVersionGetServiceResponse.java
  src/test/java/com/soptie/server/member/service/MemberServiceImplTest.java
  src/test/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImplTest.java
  src/test/java/com/soptie/server/memberRoutine/service/integration/MemberDailyRoutineServiceIntegrationTest.java
Labels: sohyeon, fix

#235 [REFACTOR] Member, Auth DTO 네이밍 및 분리
  src/main/java/com/soptie/server/auth/controller/AuthApi.java
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/controller/dto/request/SignInRequest.java
  src/main/java/com/soptie/server/auth/controller/dto/response/SignInResponse.java
  src/main/java/com/soptie/server/auth/controller/dto/response/TokenGetResponse.java
  src/main/java/com/soptie/server/auth/dto/TokenResponse.java
  src/main/java/com/soptie/server/auth/service/AuthService.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/auth/service/dto/request/SignInServiceRequest.java
  src/main/java/com/soptie/server/auth/service/dto/request/TokenGetServiceRequest.java
  src/main/java/com/soptie/server/auth/service/dto/response/SignInServiceResponse.java
  src/main/java/com/soptie/server/auth/service/dto/response/TokenGetServiceResponse.java
  src/main/java/com/soptie/server/member/controller/MemberApi.java
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/java/com/soptie/server/member/controller/dto/request/MemberProfileCreateRequest.java
  src/main/java/com/soptie/server/member/controller/dto/response/MemberCottonCountGetResponse.java
  src/main/java/com/soptie/server/member/controller/dto/response/MemberHomeInfoGetResponse.java
  src/main/java/com/soptie/server/member/dto/CottonCountResponse.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/member/service/dto/request/CottonGiveServiceRequest.java
  src/main/java/com/soptie/server/member/service/dto/request/MemberHomeInfoGetServiceRequest.java
  src/main/java/com/soptie/server/member/service/dto/request/MemberProfileCreateServiceRequest.java
  src/main/java/com/soptie/server/member/service/dto/response/MemberCottonCountGetServiceResponse.java
  src/main/java/com/soptie/server/member/service/dto/response/MemberHomeInfoGetServiceResponse.java
  src/test/java/com/soptie/server/auth/service/AuthServiceImplTest.java
  src/test/java/com/soptie/server/member/service/MemberServiceImplTest.java
Labels: chan

#238 [REFACTOR] 테마 목록 조회 API 이동
  src/main/java/com/soptie/server/common/support/ExpressionGenerator.java
  src/main/java/com/soptie/server/common/support/RepositoryAdapter.java
  src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineApi.java
  src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineApi.java
  src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/dto/HappinessThemesResponse.java
  src/main/java/com/soptie/server/routine/message/SuccessMessage.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryImpl.java
  src/main/java/com/soptie/server/routine/repository/happiness/theme/HappinessThemeCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/theme/HappinessThemeRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/theme/HappinessThemeRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/daily/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/daily/DailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/daily/dto/DailyThemeListGetServiceResponse.java
  src/main/java/com/soptie/server/theme/adapter/ThemeFinder.java
  src/main/java/com/soptie/server/theme/controller/v1/DailyThemeApiV1.java
  src/main/java/com/soptie/server/theme/controller/v1/DailyThemeControllerV1.java
  src/main/java/com/soptie/server/theme/controller/v1/HappinessThemeApiV1.java
  src/main/java/com/soptie/server/theme/controller/v1/HappinessThemeControllerV1.java
  src/main/java/com/soptie/server/theme/controller/v1/dto/response/DailyThemeListGetResponse.java
  src/main/java/com/soptie/server/theme/controller/v1/dto/response/HappinessThemeListGetResponse.java
  src/main/java/com/soptie/server/theme/entity/Theme.java
  src/main/java/com/soptie/server/theme/entity/ThemeImageInfo.java
  src/main/java/com/soptie/server/theme/message/ThemeSuccessMessage.java
  src/main/java/com/soptie/server/theme/repository/ThemeCustomRepository.java
  src/main/java/com/soptie/server/theme/repository/ThemeRepository.java
  src/main/java/com/soptie/server/theme/repository/ThemeRepositoryImpl.java
  src/main/java/com/soptie/server/theme/service/ThemeService.java
  src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java
  src/test/java/com/soptie/server/routine/repository/daily/DailyRoutineRepositoryTest.java
  src/test/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryTest.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceImplTest.java
  src/test/java/com/soptie/server/routine/service/HappinessRoutineServiceImplTest.java
  src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
  src/test/java/com/soptie/server/theme/repository/ThemeRepositoryTest.java
  src/test/java/com/soptie/server/theme/service/ThemeServiceTest.java
Labels: sohyeon, fix
