Repository Team-Sopetit/Sopetit-server, pull requests merged in 2024-08, with the labels that each got.

#312 [ADD] 데일리 루틴 달성 취소 로직 추가
  src/main/java/com/soptie/server/memberroutine/controller/v1/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberroutine/controller/v1/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberroutine/controller/v1/dto/response/MemberDailyRoutineAchieveResponse.java
  src/main/java/com/soptie/server/memberroutine/entity/MemberRoutine.java
  src/main/java/com/soptie/server/memberroutine/service/MemberRoutineUpdateService.java
  src/main/java/com/soptie/server/memberroutine/service/dto/response/MemberRoutineAchieveServiceResponse.java
  src/test/java/com/soptie/server/memberroutine/service/MemberRoutineServiceTest.java
Labels: fix

#315 [REFACTOR] 메이커 조회 수정
  src/main/java/com/soptie/server/maker/adapter/MakerFinder.java
  src/main/java/com/soptie/server/maker/controller/dto/response/MakerListAcquireResponse.java
  src/main/java/com/soptie/server/maker/entity/Maker.java
  src/main/java/com/soptie/server/maker/repository/MakerCustomRepository.java
  src/main/java/com/soptie/server/maker/repository/MakerRepository.java
  src/main/java/com/soptie/server/maker/repository/MakerRepositoryImpl.java
  src/main/java/com/soptie/server/maker/repository/dto/MakerThemeResponse.java
  src/main/java/com/soptie/server/maker/service/MakerService.java
  src/main/java/com/soptie/server/maker/service/dto/MakerListAcquireServiceResponse.java
  src/test/java/com/soptie/server/maker/service/MakerServiceTest.java
  src/test/java/com/soptie/server/maker/service/integration/MakerServiceIntegrationTest.java
  src/test/java/com/soptie/server/support/fixture/MakerFixture.java
Labels: chan, refactor

#317 [FEAT] 데일리 루틴 다중 추가 api
  src/main/java/com/soptie/server/memberroutine/controller/v1/dto/request/MemberDailyRoutinesCreateRequest.java
  src/main/java/com/soptie/server/memberroutine/controller/v2/MemberDailyRoutineControllerV2.java
  src/main/java/com/soptie/server/memberroutine/controller/v2/docs/MemberDailyRoutineControllerV2Docs.java
  src/main/java/com/soptie/server/memberroutine/service/MemberRoutineCreateService.java
  src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java
  src/main/java/com/soptie/server/routine/repository/RoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
Labels: sohyeon, feat

#318 [REFACTOR] 데일리 루틴 다중 추가 api 수정
  src/main/java/com/soptie/server/memberroutine/controller/v2/MemberDailyRoutineControllerV2.java
  src/main/java/com/soptie/server/memberroutine/controller/v2/docs/MemberDailyRoutineControllerV2Docs.java
  src/main/java/com/soptie/server/memberroutine/controller/v2/dto/response/MemberDailyRoutinesCreateResponse.java
  src/main/java/com/soptie/server/memberroutine/service/MemberRoutineCreateService.java
  src/main/java/com/soptie/server/memberroutine/service/dto/response/MemberDailyRoutinesCreateServiceResponse.java
Labels: chan, fix, refactor

#327 [REFACTOR] challenge api 리팩토링
  src/main/java/com/soptie/server/api/controller/ChallengeApi.java
  src/main/java/com/soptie/server/api/controller/ChallengeRoutineV2Api.java
  src/main/java/com/soptie/server/api/controller/MemberChallengeRoutineV2Api.java
  src/main/java/com/soptie/server/api/controller/docs/ChallengeApiDocs.java
  src/main/java/com/soptie/server/api/controller/dto/response/ErrorResponse.java
  src/main/java/com/soptie/server/api/controller/dto/response/challenge/GetChallengesByMemberResponse.java
  src/main/java/com/soptie/server/api/controller/dto/response/memberroutine/MemberChallengeRoutineAcquireResponseV2.java
  src/main/java/com/soptie/server/api/controller/dto/response/routine/ChallengeRoutineListAcquireResponseV2.java
  src/main/java/com/soptie/server/api/controller/generic/SuccessMessage.java
  src/main/java/com/soptie/server/api/web/advice/ErrorHandler.java
  src/main/java/com/soptie/server/common/exception/AuthException.java
  src/main/java/com/soptie/server/common/exception/DollException.java
  src/main/java/com/soptie/server/common/exception/MakerException.java
  src/main/java/com/soptie/server/common/exception/MemberDollException.java
  src/main/java/com/soptie/server/common/exception/MemberException.java
  src/main/java/com/soptie/server/common/exception/RoutineException.java
  src/main/java/com/soptie/server/common/exception/ThemeException.java
  src/main/java/com/soptie/server/common/message/AuthErrorCode.java
  src/main/java/com/soptie/server/common/message/DollErrorCode.java
  src/main/java/com/soptie/server/common/message/MakerErrorCode.java
  src/main/java/com/soptie/server/common/message/MemberErrorCode.java
  src/main/java/com/soptie/server/common/message/MemberRoutineSuccessMassage.java
  src/main/java/com/soptie/server/common/message/RoutineErrorCode.java
  src/main/java/com/soptie/server/common/message/ThemeErrorCode.java
  src/main/java/com/soptie/server/domain/auth/AuthServiceImpl.java
  src/main/java/com/soptie/server/domain/challenge/Challenge.java
  src/main/java/com/soptie/server/domain/challenge/ChallengeService.java
  src/main/java/com/soptie/server/domain/challenge/Mission.java
  src/main/java/com/soptie/server/domain/doll/DollServiceImpl.java
  src/main/java/com/soptie/server/domain/memberdoll/MemberDollServiceImpl.java
  src/main/java/com/soptie/server/domain/membermission/MemberMission.java
  src/main/java/com/soptie/server/domain/memberroutine/MemberChallengeRoutineAcquireServiceRequest.java
  src/main/java/com/soptie/server/domain/memberroutine/MemberChallengeRoutineAcquireServiceResponse.java
  src/main/java/com/soptie/server/domain/routine/ChallengeRoutineListAcquireServiceResponse.java
  src/main/java/com/soptie/server/domain/routine/ChallengeVO.java
  src/main/java/com/soptie/server/domain/routine/HappinessSubRoutineListGetServiceRequest.java
  src/main/java/com/soptie/server/domain/routine/HappinessSubRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/domain/routine/RoutineService.java
  src/main/java/com/soptie/server/external/AppleServiceImpl.java
  src/main/java/com/soptie/server/external/KakaoServiceImpl.java
  src/main/java/com/soptie/server/persistence/adapter/ChallengeAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/ChallengeFinder.java
  src/main/java/com/soptie/server/persistence/adapter/DollFinder.java
  src/main/java/com/soptie/server/persistence/adapter/MemberMissionAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/MissionAdapter.java
  src/main/java/com/soptie/server/persistence/entity/MissionEntity.java
  src/main/java/com/soptie/server/persistence/repository/ChallengeRepository.java
  src/main/java/com/soptie/server/persistence/repository/DeletedMemberRoutineRepository.java
  src/main/java/com/soptie/server/persistence/repository/MemberMissionRepository.java
  src/main/java/com/soptie/server/persistence/repository/MemberRoutineCustomRepository.java
  src/main/java/com/soptie/server/persistence/repository/MemberRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/persistence/repository/MissionRepository.java
  src/main/java/com/soptie/server/persistence/repository/RoutineCustomRepository.java
  src/main/java/com/soptie/server/persistence/repository/RoutineRepository.java
  src/main/java/com/soptie/server/persistence/repository/RoutineRepositoryImpl.java
  src/test/java/com/soptie/server/domain/member/MemberServiceTest.java
Labels: refactor

#328 [REFACTOR] conversation api
  src/main/java/com/soptie/server/domain/conversation/Conversation.java
  src/main/java/com/soptie/server/domain/member/MemberService.java
  src/main/java/com/soptie/server/persistence/adapter/ConversationAdapter.java
  src/test/java/com/soptie/server/domain/member/MemberServiceTest.java
Labels: refactor

#330 [REFACTOR] MemberMission API
  src/main/java/com/soptie/server/api/controller/MemberChallengeRoutineV2Api.java
  src/main/java/com/soptie/server/api/controller/MemberMissionApi.java
  src/main/java/com/soptie/server/api/controller/MemberMissionApiV2.java
  src/main/java/com/soptie/server/api/controller/docs/MemberMissionApiDocs.java
  src/main/java/com/soptie/server/api/controller/docs/MemberMissionApiV2Docs.java
  src/main/java/com/soptie/server/api/controller/dto/request/membermission/CreateMemberMissionRequest.java
  src/main/java/com/soptie/server/api/controller/dto/request/membermission/MemberHappinessRoutineRequest.java
  src/main/java/com/soptie/server/api/controller/dto/response/membermission/CreateMemberMissionResponse.java
  src/main/java/com/soptie/server/api/controller/dto/response/membermission/GetMemberMissionResponse.java
  src/main/java/com/soptie/server/api/controller/dto/response/membermission/MemberChallengeRoutineAcquireResponseV2.java
  src/main/java/com/soptie/server/common/exception/ExceptionCode.java
  src/main/java/com/soptie/server/domain/membermission/MemberMission.java
  src/main/java/com/soptie/server/domain/membermission/MemberMissionService.java
  src/main/java/com/soptie/server/domain/membermission/MemberRoutineUpdateService.java
  src/main/java/com/soptie/server/persistence/adapter/ChallengeAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/MemberMissionAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/MissionAdapter.java
  src/main/java/com/soptie/server/persistence/entity/MemberMissionEntity.java
  src/main/java/com/soptie/server/persistence/entity/MemberRoutineEntity.java
  src/main/java/com/soptie/server/persistence/repository/MemberMissionRepository.java
  src/test/java/com/soptie/server/domain/maker/MakerServiceIntegrationTest.java
Labels: refactor

#331 [REFACTOR] auth 관련 리팩토링
  src/main/java/com/soptie/server/api/controller/AuthApi.java
  src/main/java/com/soptie/server/api/controller/docs/AuthApiDocs.java
  src/main/java/com/soptie/server/api/controller/dto/request/auth/SignInRequest.java
  src/main/java/com/soptie/server/api/controller/dto/response/auth/SignInResponse.java
  src/main/java/com/soptie/server/api/controller/dto/response/auth/TokenGetResponse.java
  src/main/java/com/soptie/server/api/controller/generic/SuccessMessage.java
  src/main/java/com/soptie/server/common/exception/ExceptionCode.java
  src/main/java/com/soptie/server/domain/auth/AuthService.java
  src/main/java/com/soptie/server/domain/auth/SignInServiceRequest.java
  src/main/java/com/soptie/server/domain/auth/SignInServiceResponse.java
  src/main/java/com/soptie/server/domain/member/Member.java
  src/main/java/com/soptie/server/external/oauth/AppleServiceImpl.java
  src/main/java/com/soptie/server/external/oauth/KakaoServiceImpl.java
  src/main/java/com/soptie/server/persistence/adapter/MemberAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/MemberDollAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/MemberMissionAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/MemberRoutineAdapter.java
  src/main/java/com/soptie/server/persistence/entity/MemberEntity.java
  src/main/java/com/soptie/server/persistence/repository/MemberDollRepository.java
  src/main/java/com/soptie/server/persistence/repository/MemberMissionRepository.java
  src/main/java/com/soptie/server/persistence/repository/MemberRoutineRepository.java
Labels: chan, refactor

#332 [REFACTOR] maker 관련 리팩토링
  src/main/java/com/soptie/server/api/controller/MakerApi.java
  src/main/java/com/soptie/server/api/controller/ThemeApi.java
  src/main/java/com/soptie/server/api/controller/docs/MakerApiDocs.java
  src/main/java/com/soptie/server/api/controller/dto/response/maker/GetMakerListResponse.java
  src/main/java/com/soptie/server/api/controller/dto/response/maker/MakerListAcquireResponse.java
  src/main/java/com/soptie/server/api/controller/dto/response/maker/MakerThemeResponse.java
  src/main/java/com/soptie/server/api/controller/generic/SuccessMessage.java
  src/main/java/com/soptie/server/domain/maker/MakerService.java
  src/main/java/com/soptie/server/persistence/adapter/MakerAdapter.java
  src/main/java/com/soptie/server/persistence/adapter/ThemeAdapter.java
  src/main/java/com/soptie/server/persistence/repository/MakerRepository.java
  src/main/java/com/soptie/server/persistence/repository/ThemeCustomRepository.java
  src/main/java/com/soptie/server/persistence/repository/ThemeRepository.java
  src/main/java/com/soptie/server/persistence/repository/ThemeRepositoryImpl.java
Labels: chan, refactor

#323 [FIX] CD 트리거 변경
  .github/workflows/deploy.yml
Labels: sohyeon, fix

#337 [FIX] API version1 싱크 통일
  src/main/java/com/soptie/server/api/controller/docs/AuthApiDocs.java
  src/main/java/com/soptie/server/api/controller/dto/response/member/GetHomeInfoResponse.java
  src/main/java/com/soptie/server/temporary/TemporaryApi.java
  src/main/java/com/soptie/server/temporary/data/ThemeData.java
  src/main/java/com/soptie/server/temporary/dto/CreateMemberDailyRoutine.java
  src/main/java/com/soptie/server/temporary/dto/DailyRoutineThemesResponse.java
  src/main/java/com/soptie/server/temporary/dto/DailyRoutinesResponse.java
  src/main/java/com/soptie/server/temporary/dto/DollResponse.java
  src/main/java/com/soptie/server/temporary/dto/GetDailyRoutinesResponse.java
  src/main/java/com/soptie/server/temporary/dto/GetHappinessRoutinesResponse.java
  src/main/java/com/soptie/server/temporary/dto/GetHappinessSubRoutinesResponse.java
  src/main/java/com/soptie/server/temporary/dto/GetMemberDailyRoutinesResponse.java
  src/main/java/com/soptie/server/temporary/dto/HappinessRoutineThemesResponse.java
  src/main/java/com/soptie/server/temporary/dto/MemberHappinessRoutinesResponse.java
Labels: fix

#340 [ADD] 솜뭉치 개수가 0 이하일 경우 예외 처리 추가
  src/main/java/com/soptie/server/api/web/advice/ErrorHandler.java
  src/main/java/com/soptie/server/domain/member/MemberCotton.java
  src/main/java/com/soptie/server/domain/member/MemberService.java
Labels: fix

#341 [DEPLOY] 실서버 배포
  src/main/java/com/soptie/server/api/web/advice/ErrorHandler.java
  src/main/java/com/soptie/server/domain/member/MemberCotton.java
  src/main/java/com/soptie/server/domain/member/MemberService.java
Labels: deploy
