Repository Team-Sopetit/Sopetit-server, pull requests merged in 2024-05, with the labels that each got.

#242 [REFACTOR] 데일리 루틴 API 재구성
  src/main/java/com/soptie/server/common/handler/ErrorHandler.java
  src/main/java/com/soptie/server/member/adapter/MemberFinder.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/entity/MemberRoutine.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/daily/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java
  src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/controller/v1/DailyRoutineApiV1.java
  src/main/java/com/soptie/server/routine/controller/v1/DailyRoutineControllerV1.java
  src/main/java/com/soptie/server/routine/controller/v1/dto/response/DailyRoutineListByThemeGetResponse.java
  src/main/java/com/soptie/server/routine/controller/v1/dto/response/DailyRoutineListByThemesGetResponse.java
  src/main/java/com/soptie/server/routine/entity/Routine.java
  src/main/java/com/soptie/server/routine/exception/RoutineException.java
  src/main/java/com/soptie/server/routine/message/RoutineErrorCode.java
  src/main/java/com/soptie/server/routine/message/RoutineSuccessMessage.java
  src/main/java/com/soptie/server/routine/repository/RoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/RoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/RoutineService.java
  src/main/java/com/soptie/server/routine/service/daily/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/daily/DailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/dto/request/DailyRoutineListByThemeGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/request/DailyRoutineListByThemesGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/response/DailyRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/theme/adapter/ThemeFinder.java
  src/main/java/com/soptie/server/theme/exception/ThemeException.java
  src/main/java/com/soptie/server/theme/message/ThemeErrorCode.java
  src/test/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImplTest.java
  src/test/java/com/soptie/server/routine/repository/daily/DailyRoutineRepositoryTest.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceImplTest.java
  src/test/java/com/soptie/server/routine/service/RoutineServiceIntegrationTest.java
  src/test/java/com/soptie/server/support/fixture/MemberRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/RoutineFixture.java
Labels: sohyeon, refactor

#246 [REFACTOR] 행복 루틴 관련 API 재구성
  src/main/java/com/soptie/server/common/dto/SuccessResponse.java
  src/main/java/com/soptie/server/routine/adapter/ChallengeFinder.java
  src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java
  src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/controller/v1/HappinessRoutineControllerV1.java
  src/main/java/com/soptie/server/routine/controller/v1/api/HappinessRoutineApiV1.java
  src/main/java/com/soptie/server/routine/controller/v1/dto/response/HappinessRoutineListGetResponse.java
  src/main/java/com/soptie/server/routine/controller/v1/dto/response/HappinessSubRoutineListGetResponse.java
  src/main/java/com/soptie/server/routine/dto/HappinessRoutinesResponse.java
  src/main/java/com/soptie/server/routine/dto/HappinessSubRoutinesResponse.java
  src/main/java/com/soptie/server/routine/repository/ChallengeRepository.java
  src/main/java/com/soptie/server/routine/repository/RoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/RoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessSubRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessSubRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/RoutineService.java
  src/main/java/com/soptie/server/routine/service/dto/request/HappinessRoutineListGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/request/HappinessSubRoutineListGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/response/HappinessRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/routine/service/dto/response/HappinessSubRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/theme/entity/Theme.java
  src/test/java/com/soptie/server/routine/service/integration/RoutineServiceIntegrationTest.java
  src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
Labels: sohyeon, seungbin, refactor

#249 [DELETE] 사용하지 않는 Entity 삭제
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/adapter/MemberRoutineSaver.java
  src/main/java/com/soptie/server/memberRoutine/entity/MemberRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/CompletedMemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/happiness/MemberHappinessRoutine.java
  src/main/java/com/soptie/server/memberRoutine/repository/CompletedMemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineCustomRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/memberRoutine/repository/dto/MemberChallengeResponse.java
  src/main/java/com/soptie/server/routine/adapter/ChallengeFinder.java
  src/main/java/com/soptie/server/routine/entity/Challenge.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java
  src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
  src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
  src/main/java/com/soptie/server/routine/repository/ChallengeRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessSubRoutineRepository.java
  src/main/java/com/soptie/server/routine/service/dto/response/HappinessSubRoutineListGetServiceResponse.java
  src/test/java/com/soptie/server/memberRoutine/service/integration/MemberRoutineServiceIntegrationTest.java
  src/test/java/com/soptie/server/routine/service/integration/RoutineServiceIntegrationTest.java
  src/test/java/com/soptie/server/support/fixture/ChallengeFixture.java
  src/test/java/com/soptie/server/support/fixture/CompletedMemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/DailyRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/DailyThemeFixture.java
  src/test/java/com/soptie/server/support/fixture/HappinessRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/HappinessSubRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/HappinessThemeFixture.java
  src/test/java/com/soptie/server/support/fixture/MemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/support/fixture/MemberHappinessRoutineFixture.java
Labels: sohyeon, delete

#253 [HOTFIX] 행복 루틴 이슈 대응
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineService.java
  src/test/java/com/soptie/server/memberRoutine/service/MemberRoutineServiceTest.java
Labels: hotfix

#254 [HOTFIX] 행복 루틴 조회
  src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java
  src/main/java/com/soptie/server/routine/repository/RoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/RoutineService.java
  src/main/java/com/soptie/server/routine/service/dto/request/HappinessRoutineListGetServiceRequest.java
Labels: hotfix

#255 [HOTFIX] 전체 조회 이슈 대응
  src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
Labels: sohyeon, hotfix

#256 [HOTFIX] 데일리 루틴 조회 배경 이미지 이슈 대응
  src/main/java/com/soptie/server/routine/service/dto/response/DailyRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/theme/entity/ThemeImageInfo.java
  src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
Labels: sohyeon, hotfix

#257 [HOTFIX] 데일리 루틴 조회 배경 이미지 이슈 대응
  src/main/java/com/soptie/server/theme/controller/v1/dto/response/DailyThemeListGetResponse.java
  src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java
Labels: sohyeon, hotfix

#258 [HOTFIX] 데일리 루틴 아이콘 이미지 이슈 대응
  src/main/java/com/soptie/server/theme/controller/v1/dto/response/DailyThemeListGetResponse.java
  src/main/java/com/soptie/server/theme/entity/ThemeImageInfo.java
  src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java
  src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
Labels: sohyeon, chan, hotfix

#259 [HOTFIX] 데일리 루틴 아이콘 이미지 이슈 대응
  src/main/java/com/soptie/server/memberRoutine/repository/dto/MemberRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberDailyRoutineListGetServiceResponse.java
Labels: sohyeon, chan, hotfix

#260 [HOTFIX] 구버전 이미지 이슈 대응
  src/main/java/com/soptie/server/routine/service/dto/response/DailyRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/routine/service/dto/response/HappinessSubRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/theme/entity/ThemeImageInfo.java
  src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java
  src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
Labels: sohyeon, chan, hotfix

#261 [HOTFIX] 구버전 이미지 이슈 대응
  src/main/java/com/soptie/server/memberRoutine/controller/v1/dto/response/MemberHappinessRoutineGetResponse.java
  src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberHappinessRoutineGetServiceResponse.java
Labels: sohyeon, hotfix

#263 [FIX] 안드로이드 앱 버전 업데이트
  src/main/java/com/soptie/server/common/config/ValueConfig.java
Labels: sohyeon, fix

#264 [FIX] 안드로이드 버전 업데이트
  src/main/java/com/soptie/server/common/config/ValueConfig.java
Labels: sohyeon, fix

#267 [FIX] 스웨거 토큰 이슈 대응
  src/main/java/com/soptie/server/common/config/SwaggerConfig.java
Labels: sohyeon, fix

#269 [REFACTOR] 회원 루틴 서비스 분리
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/controller/v1/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/controller/v1/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/scheduler/MemberDailyRoutineScheduler.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineCreateService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineDeleteService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineReadService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineUpdateService.java
  src/test/java/com/soptie/server/member/service/MemberServiceImplTest.java
  src/test/java/com/soptie/server/memberRoutine/service/MemberRoutineServiceTest.java
  src/test/java/com/soptie/server/memberRoutine/service/integration/MemberRoutineServiceIntegrationTest.java
Labels: sohyeon, refactor

#270 [CHORE] 메소드 띄어쓰기 및 불필요한 import문 제거
  src/main/java/com/soptie/server/auth/controller/AuthApi.java
  src/main/java/com/soptie/server/auth/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soptie/server/auth/jwt/UserAuthentication.java
  src/main/java/com/soptie/server/common/config/SecurityConfig.java
  src/main/java/com/soptie/server/doll/entity/Doll.java
  src/main/java/com/soptie/server/member/controller/dto/response/MemberHomeInfoGetResponse.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/controller/v1/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/controller/v1/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/entity/MemberRoutine.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineUpdateService.java
  src/main/java/com/soptie/server/routine/entity/Challenge.java
  src/main/java/com/soptie/server/routine/service/dto/request/DailyRoutineListByThemeGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/request/DailyRoutineListByThemesGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/request/HappinessRoutineListGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/request/HappinessSubRoutineListGetServiceRequest.java
  src/main/java/com/soptie/server/routine/service/dto/response/DailyRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/routine/service/dto/response/HappinessRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/routine/service/dto/response/HappinessSubRoutineListGetServiceResponse.java
  src/main/java/com/soptie/server/theme/controller/v1/dto/response/DailyThemeListGetResponse.java
  src/main/java/com/soptie/server/theme/controller/v1/dto/response/HappinessThemeListGetResponse.java
  src/main/java/com/soptie/server/theme/entity/Theme.java
  src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java
  src/main/java/com/soptie/server/version/controller/dto/response/AppVersionGetResponse.java
  src/main/java/com/soptie/server/version/service/dto/response/AppVersionGetServiceResponse.java
Labels: chan

#272 [REFACTOR] MemberService 순환 참조 문제
  src/main/java/com/soptie/server/conversation/adapter/ConversationFinder.java
  src/main/java/com/soptie/server/doll/adapter/DollFinder.java
  src/main/java/com/soptie/server/member/adapter/MemberDeleter.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberDoll/adapter/MemberDollSaver.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineCreateService.java
  src/test/java/com/soptie/server/member/service/MemberServiceImplTest.java
Labels: chan, refactor
