Repository Team-Sopetit/Sopetit-server, pull requests merged in 2024-01, with the labels that each got.

#3 [ADD] Routine 엔티티 구체화
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/entity/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/MemberHappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
Labels: add, sohyeon

#6 [INIT] ERD 설계
  build.gradle
  src/main/java/com/soptie/server/common/config/JpaAuditingConfig.java
  src/main/java/com/soptie/server/common/config/TimezoneConfig.java
  src/main/java/com/soptie/server/common/entity/BaseTime.java
  src/main/java/com/soptie/server/conversation/entity/Conversation.java
  src/main/java/com/soptie/server/doll/entity/Doll.java
  src/main/java/com/soptie/server/doll/entity/DollImage.java
  src/main/java/com/soptie/server/doll/entity/DollType.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/member/entity/SocialType.java
  src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/CompletedMemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/happiness/MemberHappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java
  src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
  src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
Labels: add, sohyeon

#10 [INIT] RestDocs&Swagger 환경 세팅
  build.gradle
  src/main/java/com/soptie/server/test/TestController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/base/BaseControllerTest.java
  src/test/java/com/soptie/server/test/TestControllerTest.java
Labels: sohyeon, init

#18 [INIT] DB 설정 정보 추가
  .github/workflows/CI.yml
  .gitignore
  src/main/java/com/soptie/server/doll/entity/Doll.java
  src/main/java/com/soptie/server/doll/entity/DollType.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/test
Labels: sohyeon, init

#17 [FEAT] 데일리 루틴 테마 리스트 조회
  build.gradle
  src/main/java/com/soptie/server/common/config/JpaQueryFactoryConfig.java
  src/main/java/com/soptie/server/common/dto/Response.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/dto/DailyThemesResponse.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java
  src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java
  src/main/java/com/soptie/server/routine/message/ResponseMessage.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
Labels: sohyeon, feat

#21 [FEAT] 테마 리스트 별 루틴 리스트 조회
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesResponse.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java
  src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java
  src/main/java/com/soptie/server/routine/message/ResponseMessage.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/fixture/DailyRoutineFixture.java
Labels: sohyeon, feat

#23 [FEAT] 테마 별 데일리 루틴 리스트 조회
  src/main/java/com/soptie/server/common/handler/ErrorHandler.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/message/ErrorMessage.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
Labels: sohyeon, feat

#25 [FEAT] 인형 이미지 조회
  src/main/java/com/soptie/server/doll/controller/DollController.java
  src/main/java/com/soptie/server/doll/dto/DollImageResponse.java
  src/main/java/com/soptie/server/doll/entity/Doll.java
  src/main/java/com/soptie/server/doll/entity/DollImage.java
  src/main/java/com/soptie/server/doll/message/ErrorMessage.java
  src/main/java/com/soptie/server/doll/message/ResponseMessage.java
  src/main/java/com/soptie/server/doll/repository/DollRepository.java
  src/main/java/com/soptie/server/doll/service/DollService.java
  src/main/java/com/soptie/server/doll/service/DollServiceImpl.java
  src/test/java/com/soptie/server/doll/controller/DollControllerTest.java
  src/test/java/com/soptie/server/doll/fixture/DollFixture.java
Labels: sohyeon, feat

#31 [FIX] 행복 루틴 엔티티 수정
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
Labels: sohyeon, fix

#44 [HOTFIX] 에러 대응
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/doll/controller/DollControllerTest.java
Labels: bug, sohyeon, hotfix

#46 [FIX] 배포 jar 이름 수정
  scripts/deploy.sh
Labels: bug, sohyeon, hotfix

#42 [INIT] 시큐리티 및 jwt 기초 세팅
  build.gradle
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/dto/SignInRequest.java
  src/main/java/com/soptie/server/auth/dto/SignInResponse.java
  src/main/java/com/soptie/server/auth/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soptie/server/auth/jwt/JwtTokenProvider.java
  src/main/java/com/soptie/server/auth/jwt/JwtValidationType.java
  src/main/java/com/soptie/server/auth/jwt/UserAuthentication.java
  src/main/java/com/soptie/server/auth/message/ErrorMessage.java
  src/main/java/com/soptie/server/auth/message/ResponseMessage.java
  src/main/java/com/soptie/server/auth/service/AuthService.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/auth/service/KakaoService.java
  src/main/java/com/soptie/server/auth/service/KakaoServiceImpl.java
  src/main/java/com/soptie/server/auth/vo/Token.java
  src/main/java/com/soptie/server/common/config/RestTemplateConfig.java
  src/main/java/com/soptie/server/common/config/SecurityConfig.java
  src/main/java/com/soptie/server/common/config/ValueConfig.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/member/message/ErrorMessage.java
  src/main/java/com/soptie/server/member/repository/MemberRepository.java
  src/main/resources/application-dev.yml
Labels: chan, init

#51 [HOTFIX] 빌드 에러 대응
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/base/BaseControllerTest.java
Labels: bug, hotfix

#52 [CHORE] 권한 경로 추가, 테스트 일부 삭제
  src/main/java/com/soptie/server/common/config/SecurityConfig.java
  src/test/java/com/soptie/server/ServerApplicationTests.java
Labels: bug, hotfix

#34 [FEAT] 회원 데일리 루틴 추가
  src/main/java/com/soptie/server/member/message/ErrorMessage.java
  src/main/java/com/soptie/server/member/repository/MemberRepository.java
  src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutineRequest.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/message/ResponseMessage.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/message/ErrorMessage.java
  src/test/java/com/soptie/server/ServerApplicationTests.java
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberDailyRoutineFixture.java
Labels: sohyeon, feat

#37 [FEAT] 회원 데일리 루틴 삭제
  src/main/java/com/soptie/server/common/handler/ErrorHandler.java
  src/main/java/com/soptie/server/member/message/ErrorMessage.java
  src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/CompletedMemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/message/ResponseMessage.java
  src/main/java/com/soptie/server/memberRoutine/repository/CompletedMemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
Labels: sohyeon, delete

#39 [FEAT] 회원 데일리 루틴 달성
  src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/dto/AchievedMemberDailyRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/message/ResponseMessage.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
Labels: sohyeon, patch

#55 [TEST] 소셜 로그인 api 테스트
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
Labels: chan, test

#56 [ADD] 권한 허용 경로 추가
  src/main/java/com/soptie/server/common/config/SecurityConfig.java
Labels: add, sohyeon

#41 [FEAT] 회원 별 데일리 루틴 리스트 조회
  src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutinesResponse.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/message/ResponseMessage.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineCustomRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/routine/fixture/DailyRoutineFixture.java
Labels: sohyeon, feat

#67 [FIX] 테스트코드 누락 해결: 식별자 분리
  src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
Labels: bug, sohyeon, hotfix

#48 [FEAT] 행복루틴 테마 리스트 조회
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/dto/HappinessThemesResponse.java
  src/main/java/com/soptie/server/routine/message/ResponseMessage.java
  src/main/java/com/soptie/server/routine/repository/happiness/theme/HappinessThemeCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/theme/HappinessThemeRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/theme/HappinessThemeRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
Labels: feat, seungbin

#68 [FEAT] 프로필 생성 API
  src/main/java/com/soptie/server/doll/service/DollService.java
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/java/com/soptie/server/member/dto/MemberProfileRequest.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/member/message/ErrorMessage.java
  src/main/java/com/soptie/server/member/message/ResponseMessage.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
  src/main/java/com/soptie/server/memberDoll/repository/MemberDollRepository.java
  src/main/java/com/soptie/server/memberDoll/service/MemberDollService.java
  src/main/java/com/soptie/server/memberDoll/service/MemberDollServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: chan, feat

#64 [ADD] 데일리 솜 개수 추가 로직 추가
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
Labels: add, sohyeon

#65 [FIX] stream 통일
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/routine/fixture/DailyRoutineFixture.java
Labels: sohyeon, fix

#72 [FEAT] 루틴 달성 초기화 스케줄러
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineCustomRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/memberRoutine/scheduler/MemberDailyRoutineScheduler.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/resources/application-dev.yml
Labels: sohyeon, feat

#73 [FIX] 정렬 기준 KR로 변경
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
Labels: sohyeon, fix

#54 [FEAT] 테마 별 행복루틴 리스트 조회
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/dto/HappinessRoutinesResponse.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
  src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
  src/main/java/com/soptie/server/routine/message/ResponseMessage.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: feat, seungbin

#82 [FIX] 병합 충돌 대응
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/CompletedMemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/happiness/MemberHappinessRoutine.java
  src/main/java/com/soptie/server/memberRoutine/repository/CompletedMemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessSubRoutineRepository.java
Labels: sohyeon, fix

#78 [FEAT] 행복루틴 추가
  src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineRequest.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/entity/happiness/MemberHappinessRoutine.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineCustomRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessSubRoutineRepository.java
Labels: feat, seungbin

#83 [FEAT] 회원 행복 루틴 조회
  src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutinesResponse.java
  src/main/java/com/soptie/server/memberRoutine/message/ResponseMessage.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberHappinessRoutineFixture.java
Labels: sohyeon, feat, test

#87 [FEAT] 솜뭉치 주기 api
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/java/com/soptie/server/member/dto/CottonCountResponse.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/CottonType.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/member/message/ErrorMessage.java
  src/main/java/com/soptie/server/member/message/ResponseMessage.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
Labels: chan, feat, test

#88 [DELETE] 서 있는 이미지 url 삭제
  src/main/java/com/soptie/server/member/dto/MemberHomeInfoResponse.java
  src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
Labels: chan, delete

#94 [FEAT] 로그아웃 api
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/message/ResponseMessage.java
  src/main/java/com/soptie/server/auth/service/AuthService.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
Labels: chan, feat, test

#97 [FEAT] 행복루틴 삭제
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineCustomRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: feat, seungbin

#98 [FEAT] 행복루틴 달성
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: seungbin

#102 [FIX] 테마 별 행복루틴 조회에서 테마 id 값을 쿼리 값으로 변경
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepositoryImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: sohyeon, fix

#99 [TEST] 내가 만든 기능들 테스트 코드 작성하기
  src/main/java/com/soptie/server/routine/dto/HappinessRoutinesResponse.java
  src/main/java/com/soptie/server/routine/dto/HappinessThemesResponse.java
  src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/fixture/HappinessRoutineFixture.java
Labels: seungbin, test

#100 [ADD] 데일리 루틴 추가 예외처리 추가
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/message/ErrorMessage.java
Labels: add, sohyeon

#104 [HOTFIX] 테스트 실패 대응
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
Labels: bug, sohyeon, hotfix

#105 [ADD] 행복 루틴 추가 시 이미 행복 루틴을 가진 회원이면 예외 처리 추가
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: seungbin

#108 [DELETE] 회원 탈퇴
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/message/ResponseMessage.java
  src/main/java/com/soptie/server/auth/service/AuthService.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/memberDoll/repository/MemberDollRepository.java
  src/main/java/com/soptie/server/memberDoll/service/MemberDollService.java
  src/main/java/com/soptie/server/memberDoll/service/MemberDollServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/repository/CompletedMemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/service/CompletedMemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/CompletedMemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
Labels: chan, feat, test

#112 [FEAT] 행복 루틴 별 서브 행복 루틴 리스트 조회 api
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/dto/HappinessRoutinesResponse.java
  src/main/java/com/soptie/server/routine/dto/HappinessSubRoutinesResponse.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
  src/main/java/com/soptie/server/routine/message/ResponseMessage.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessSubRoutineRepository.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessSubRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessSubRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
Labels: chan, feat, test

#116 [TEST] testcode 작성하기
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberHappinessRoutineFixture.java
Labels: seungbin

#113 [REFACTOR] 종합 이슈 처리
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/message/SuccessMessage.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/doll/controller/DollController.java
  src/main/java/com/soptie/server/doll/message/SuccessMessage.java
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/member/message/ErrorMessage.java
  src/main/java/com/soptie/server/member/message/SuccessMessage.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/entity/happiness/MemberHappinessRoutine.java
  src/main/java/com/soptie/server/memberRoutine/message/SuccessMessage.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/message/SuccessMessage.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
  src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
Labels: chan

#124 [REFACTOR] 코드 스타일 통일
  src/main/java/com/soptie/server/auth/dto/SignInRequest.java
  src/main/java/com/soptie/server/auth/dto/SignInResponse.java
  src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soptie/server/auth/jwt/JwtTokenProvider.java
  src/main/java/com/soptie/server/auth/service/AuthService.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/common/dto/Response.java
  src/main/java/com/soptie/server/doll/dto/DollImageResponse.java
  src/main/java/com/soptie/server/doll/entity/Doll.java
  src/main/java/com/soptie/server/doll/entity/DollImage.java
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/java/com/soptie/server/member/dto/MemberHomeInfoResponse.java
  src/main/java/com/soptie/server/member/dto/MemberProfileRequest.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/dto/AchievedMemberDailyRoutineResponse.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutineRequest.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutinesResponse.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineRequest.java
  src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutinesResponse.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyThemesResponse.java
  src/main/java/com/soptie/server/routine/dto/HappinessRoutinesResponse.java
  src/main/java/com/soptie/server/routine/dto/HappinessSubRoutinesResponse.java
  src/main/java/com/soptie/server/routine/dto/HappinessThemesResponse.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java
  src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
  src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
  src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessSubRoutineService.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/fixture/MemberDailyRoutineFixture.java
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/fixture/DailyRoutineFixture.java
Labels: sohyeon, fix

#125 [ADD] 행복 루틴 테마 칼럼 추가
  src/main/java/com/soptie/server/routine/dto/HappinessSubRoutinesResponse.java
  src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
Labels: add, sohyeon, hotfix

#119 [CHORE] 테스트 코드 예제 작성
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesResponse.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java
  src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java
  src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java
  src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/base/BaseRepositoryTest.java
  src/test/java/com/soptie/server/base/BaseServiceTest.java
  src/test/java/com/soptie/server/config/TestJpaQueryFactoryConfig.java
  src/test/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryTest.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java
Labels: sohyeon, init

#127 [CHORE] 커스텀 예외
  src/main/java/com/soptie/server/auth/exception/AuthException.java
  src/main/java/com/soptie/server/auth/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/soptie/server/auth/message/ErrorCode.java
  src/main/java/com/soptie/server/auth/message/ErrorMessage.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/common/handler/ErrorHandler.java
  src/main/java/com/soptie/server/doll/exception/DollException.java
  src/main/java/com/soptie/server/doll/message/ErrorCode.java
  src/main/java/com/soptie/server/doll/message/ErrorMessage.java
  src/main/java/com/soptie/server/doll/service/DollServiceImpl.java
  src/main/java/com/soptie/server/member/exception/MemberException.java
  src/main/java/com/soptie/server/member/message/ErrorCode.java
  src/main/java/com/soptie/server/member/message/ErrorMessage.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberDoll/service/MemberDollServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/exception/RoutineException.java
  src/main/java/com/soptie/server/routine/message/ErrorCode.java
  src/main/java/com/soptie/server/routine/message/ErrorMessage.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: add, sohyeon

#130 [ADD] 회원 행복루틴 조회, 204 분기 처리 추가
  src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
Labels: add, sohyeon

#128 [FEAT] 애플 로그인 api
  src/main/java/com/soptie/server/auth/message/ErrorCode.java
  src/main/java/com/soptie/server/auth/service/AppleService.java
  src/main/java/com/soptie/server/auth/service/AppleServiceImpl.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/auth/service/KakaoServiceImpl.java
  src/main/java/com/soptie/server/common/config/ValueConfig.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
Labels: chan, feat

#133 [CHORE] 변수명 수정
  src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineRequest.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java
Labels: chan, hotfix

#135 [FIX] 응답 데이터 수정
  src/main/java/com/soptie/server/routine/dto/HappinessSubRoutinesResponse.java
Labels: sohyeon, fix

#138 [ADD] 회원의 인형 존재 여부에 따라 예외 처리 추가
  src/main/java/com/soptie/server/member/message/ErrorCode.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
Labels: add, sohyeon

#140 [FIX] 메소드 수정
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
Labels: sohyeon, hotfix

#136 [ADD] 프로필 존재 여부 response에 추가
  src/main/java/com/soptie/server/auth/dto/SignInResponse.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
Labels: add, chan

#145 [ADD] 외부 API 예외 처리
  src/main/java/com/soptie/server/auth/service/KakaoServiceImpl.java
Labels: add, sohyeon

#144 [REFACTOR] 코드 리팩토링
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/common/util/Constant.java
  src/main/java/com/soptie/server/doll/service/DollServiceImpl.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberDoll/service/MemberDollServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
Labels: sohyeon, fix

#148 [FIX] 데일리 루틴 삭제 수정
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
Labels: sohyeon, hotfix

#149 [FIX] 회고
  src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
Labels: sohyeon, hotfix

#153 [ADD] 테마별 데일리 루틴 조회, 배경 이미지 추가
  src/main/java/com/soptie/server/routine/dto/DailyRoutineResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesByThemeResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesByThemesResponse.java
  src/main/java/com/soptie/server/routine/dto/DailyRoutinesResponse.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/fixture/DailyRoutineFixture.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java
Labels: add, sohyeon

#155 [FIX] 테마별 데일리 루틴 조회 수정
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java
Labels: add, sohyeon

#158 [REFACTOR] 캡슐화
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
  src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
  src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java
Labels: sohyeon, fix

#161 [FIX] 데일리 솜뭉치 무한 개 생성 막기
  src/main/java/com/soptie/server/memberRoutine/entity/daily/CompletedMemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
Labels: sohyeon, hotfix

#156 [FEAT] 토큰 재발급 api
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/dto/TokenResponse.java
  src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soptie/server/auth/message/ErrorCode.java
  src/main/java/com/soptie/server/auth/message/SuccessMessage.java
  src/main/java/com/soptie/server/auth/service/AuthService.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/common/util/Constant.java
  src/main/java/com/soptie/server/member/repository/MemberRepository.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
Labels: chan, feat, test

#163 [FIX] 인형 이름 숫자 금지
  src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
Labels: chan, fix, hotfix

#165 [ADD] 회원 데일리 루틴 정렬 조건 추가
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java
Labels: add, sohyeon

#168 [FIX] 인형이 먹은 행복 솜뭉치 데이터 저장
  src/main/java/com/soptie/server/doll/message/ErrorCode.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/Member.java
Labels: sohyeon, hold review, fix

#169 [CHORE] constant 폴더로 상수 이동 및 코드 컨벤션에 맞게 수정
  src/main/java/com/soptie/server/auth/controller/AuthController.java
  src/main/java/com/soptie/server/auth/dto/TokenResponse.java
  src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soptie/server/auth/jwt/JwtValidationType.java
  src/main/java/com/soptie/server/auth/service/AppleServiceImpl.java
  src/main/java/com/soptie/server/auth/service/AuthService.java
  src/main/java/com/soptie/server/common/util/Constant.java
  src/main/java/com/soptie/server/doll/entity/DollImage.java
  src/main/java/com/soptie/server/doll/message/SuccessMessage.java
  src/main/java/com/soptie/server/doll/service/DollService.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/service/MemberService.java
  src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
  src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
  src/main/java/com/soptie/server/memberDoll/repository/MemberDollRepository.java
  src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepository.java
  src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
  src/main/java/com/soptie/server/routine/message/SuccessMessage.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineCustomRepository.java
  src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepository.java
  src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
Labels: chan

#174 [FEAT] 앱 버전 정보 조회
  src/main/java/com/soptie/server/common/config/SecurityConfig.java
  src/main/java/com/soptie/server/common/config/ValueConfig.java
  src/main/java/com/soptie/server/version/controller/VersionController.java
  src/main/java/com/soptie/server/version/dto/AppVersionResponse.java
  src/main/java/com/soptie/server/version/message/SuccessMessage.java
  src/main/java/com/soptie/server/version/service/VersionService.java
  src/main/java/com/soptie/server/version/service/VersionServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/version/controller/VersionControllerTest.java
Labels: sohyeon, feat, test

#175 [CHORE] 솜뭉치 주기 api 경로 수정
  src/main/java/com/soptie/server/member/controller/MemberController.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
Labels: chan

#176 [CHORE] 특정 값 변수 모음 클래스 병합
  src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soptie/server/auth/service/AppleServiceImpl.java
  src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
  src/main/java/com/soptie/server/common/config/ValueConfig.java
  src/main/java/com/soptie/server/common/util/Constant.java
  src/main/java/com/soptie/server/member/entity/Cotton.java
  src/main/java/com/soptie/server/member/entity/Member.java
  src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
  src/test/java/com/soptie/server/doll/controller/DollControllerTest.java
  src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
  src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
  src/test/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryTest.java
  src/test/java/com/soptie/server/test/TestControllerTest.java
  src/test/java/com/soptie/server/version/controller/VersionControllerTest.java
Labels: sohyeon, fix

#179 [FIX] 업데이트 알림 문구 수정
  src/main/java/com/soptie/server/common/config/ValueConfig.java
  src/main/java/com/soptie/server/version/dto/AppVersionResponse.java
  src/main/java/com/soptie/server/version/service/VersionServiceImpl.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/soptie/server/version/controller/VersionControllerTest.java
Labels: sohyeon, fix, hotfix

#180 [FIX] 리프레시 토큰 만료 시에도 토큰 재발급 해주는 버그 수정
  src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soptie/server/auth/message/ErrorCode.java
  src/main/java/com/soptie/server/common/config/SecurityConfig.java
Labels: chan, fix
